"""architecture platform authority

Revision ID: 11b07f8ee574
Revises: 011_report_artifacts
Create Date: 2026-09-01 17:01:36.960128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b07f8ee574'
down_revision: Union[str, None] = '011_report_artifacts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('parent_execution_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('model_revision', sa.String(length=128), nullable=True),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_digest', sa.String(length=64), nullable=False),
    sa.Column('output_schema_version', sa.String(length=128), nullable=True),
    sa.Column('output_schema_digest', sa.String(length=64), nullable=True),
    sa.Column('evidence_digest', sa.String(length=64), nullable=True),
    sa.Column('policy_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_id', sa.String(length=128), nullable=True),
    sa.Column('generation_settings', sa.JSON(), nullable=False),
    sa.Column('request_budget', sa.JSON(), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('validation_result', sa.String(length=32), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('fallback_reason', sa.String(length=128), nullable=True),
    sa.Column('escalation_reason', sa.String(length=128), nullable=True),
    sa.Column('quota_reservation_id', sa.String(length=36), nullable=True),
    sa.Column('output_digest', sa.String(length=64), nullable=True),
    sa.Column('routing_policy_version', sa.String(length=128), nullable=False),
    sa.Column('model_registry_version', sa.String(length=64), nullable=False),
    sa.Column('record_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("validation_result IN ('NOT_REQUESTED','VALID','INVALID','UNCERTAIN')", name='ck_ai_execution_validation_result'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_digest', name='uq_ai_execution_record_digest')
    )
    with op.batch_alter_table('ai_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_executions_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_capability'), ['capability'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_evidence_digest'), ['evidence_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_parent_execution_id'), ['parent_execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_policy_snapshot_id'), ['policy_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_prompt_digest'), ['prompt_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_quota_reservation_id'), ['quota_reservation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_executions_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('ai_provider_health',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('circuit_state', sa.String(length=16), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_code', sa.String(length=64), nullable=True),
    sa.Column('opened_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('probe_claimed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("circuit_state IN ('CLOSED','OPEN','HALF_OPEN')", name='ck_ai_provider_circuit_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'model', name='uq_ai_provider_health_endpoint')
    )
    with op.batch_alter_table('ai_provider_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_provider_health_circuit_state'), ['circuit_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_health_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_health_opened_until'), ['opened_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_provider_health_provider'), ['provider'], unique=False)

    op.create_table('ai_quota_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=False),
    sa.Column('window_key', sa.String(length=64), nullable=False),
    sa.Column('window_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_limit', sa.Integer(), nullable=True),
    sa.Column('input_token_limit', sa.Integer(), nullable=True),
    sa.Column('output_token_limit', sa.Integer(), nullable=True),
    sa.Column('reserved_calls', sa.Integer(), nullable=False),
    sa.Column('reserved_input_tokens', sa.Integer(), nullable=False),
    sa.Column('reserved_output_tokens', sa.Integer(), nullable=False),
    sa.Column('consumed_calls', sa.Integer(), nullable=False),
    sa.Column('consumed_input_tokens', sa.Integer(), nullable=False),
    sa.Column('consumed_output_tokens', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reserved_calls >= 0 AND consumed_calls >= 0', name='ck_ai_quota_nonnegative_calls'),
    sa.CheckConstraint('reserved_input_tokens >= 0 AND consumed_input_tokens >= 0', name='ck_ai_quota_nonnegative_input'),
    sa.CheckConstraint('reserved_output_tokens >= 0 AND consumed_output_tokens >= 0', name='ck_ai_quota_nonnegative_output'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_id', 'provider', 'model', 'window_key', name='uq_ai_quota_bucket_window')
    )
    with op.batch_alter_table('ai_quota_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_quota_buckets_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_buckets_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_buckets_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_buckets_window_ends_at'), ['window_ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_buckets_window_key'), ['window_key'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('repository_id', sa.String(length=128), nullable=True),
    sa.Column('revision_id', sa.String(length=128), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('identity_digest', sa.String(length=64), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('payload_locator', sa.String(length=1024), nullable=False),
    sa.Column('payload_size_bytes', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('producer', sa.String(length=128), nullable=False),
    sa.Column('producer_version', sa.String(length=128), nullable=False),
    sa.Column('producer_config_digest', sa.String(length=64), nullable=False),
    sa.Column('policy_snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('coverage_payload', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('retention_class', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("artifact_type IN ('REPOSITORY_REVISION','ANALYZER_RUN','SCANNER','SYMBOL_INDEX','CONTRACT','COVERAGE','EVIDENCE','CLAIM','FINDING','AI_EXECUTION','REPORT_DOCUMENT','PDF_REPORT')", name='ck_artifact_type'),
    sa.CheckConstraint("retention_class IN ('EPHEMERAL_REPOSITORY_SNAPSHOT','SOURCE_BEARING_ARTIFACT','EMBEDDING','ANALYSIS_ARTIFACT','PDF_REPORT','WORKFLOW_EVENT','AUDIT_RECORD','GITHUB_PUBLICATION_RECORD')", name='ck_artifact_retention_class'),
    sa.CheckConstraint("sensitivity IN ('INTERNAL','SOURCE_DERIVED','SECURITY_SENSITIVE','RESTRICTED')", name='ck_artifact_sensitivity'),
    sa.CheckConstraint('length(content_digest) = 64', name='ck_artifact_content_digest_length'),
    sa.CheckConstraint('length(identity_digest) = 64', name='ck_artifact_identity_digest_length'),
    sa.CheckConstraint('payload_size_bytes >= 0', name='ck_artifact_payload_size'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identity_digest', name='uq_artifact_tenant_identity'),
    sa.UniqueConstraint('tenant_id', 'payload_locator', name='uq_artifact_tenant_locator')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_revision_type', ['tenant_id', 'repository_id', 'revision_id', 'artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_content_digest'), ['content_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_coverage_status'), ['coverage_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_policy_snapshot_id'), ['policy_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_producer'), ['producer'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_retention_class'), ['retention_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_revision_id'), ['revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_chain_heads',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('head_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_digest', sa.String(length=64), nullable=True),
    sa.Column('state_digest', sa.String(length=64), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('safe_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_hash', name='uq_audit_tenant_hash'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_audit_tenant_sequence')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_hash'), ['event_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('execution_resource_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('reserved_units', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('policy_snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity_units > 0', name='ck_execution_pool_capacity'),
    sa.CheckConstraint('reserved_units >= 0 AND reserved_units <= capacity_units', name='ck_execution_pool_reserved'),
    sa.CheckConstraint('version >= 0', name='ck_execution_pool_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'scope_id', name='uq_execution_resource_pool_scope')
    )
    with op.batch_alter_table('execution_resource_pools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_resource_pools_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_pools_scope_id'), ['scope_id'], unique=False)

    op.create_table('operational_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_scope', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('policy_payload', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_scope', 'content_digest', name='uq_operational_policy_scope_digest'),
    sa.UniqueConstraint('tenant_scope', 'version', name='uq_operational_policy_scope_version')
    )
    with op.batch_alter_table('operational_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_policies_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_policies_content_digest'), ['content_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_policies_tenant_scope'), ['tenant_scope'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('deduplication_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'deduplication_key', name='uq_outbox_tenant_dedupe')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_aggregate_type'), ['aggregate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('expected_digest', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'resource_type', 'resource_id', 'operation', name='uq_reconcile_resource_op')
    )
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_records_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('telemetry_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_metrics_metric_name'), ['metric_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_metrics_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_metrics_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_metrics_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_metrics_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('ai_quota_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bucket_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=False),
    sa.Column('actual_input_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_output_tokens', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('RESERVED','COMMITTED','RELEASED','EXPIRED')", name='ck_ai_quota_reservation_state'),
    sa.ForeignKeyConstraint(['bucket_id'], ['ai_quota_buckets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', name='uq_ai_quota_reservation_execution')
    )
    with op.batch_alter_table('ai_quota_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_bucket_id'), ['bucket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_quota_reservations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('artifact_lineage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('related_artifact_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relation IN ('DERIVED_FROM','PRODUCED_BY','INVALIDATES','SUPERSEDES')", name='ck_artifact_lineage_relation'),
    sa.CheckConstraint('artifact_id != related_artifact_id', name='ck_artifact_lineage_no_self_edge'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'artifact_id', 'relation', 'related_artifact_id', name='uq_artifact_lineage_edge')
    )
    with op.batch_alter_table('artifact_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_lineage_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index('ix_artifact_lineage_incoming', ['tenant_id', 'related_artifact_id', 'relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_lineage_related_artifact_id'), ['related_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_lineage_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('artifact_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('referrer_kind', sa.String(length=64), nullable=False),
    sa.Column('referrer_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'artifact_id', 'referrer_kind', 'referrer_id', name='uq_artifact_reference_owner')
    )
    with op.batch_alter_table('artifact_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_references_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_references_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('artifact_tombstones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(request_digest) = 64', name='ck_artifact_tombstone_digest_length'),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', name='uq_artifact_tombstone')
    )
    with op.batch_alter_table('artifact_tombstones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_tombstones_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_tombstones_eligible_at'), ['eligible_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_tombstones_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_tombstones_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_tombstones_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('execution_work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('policy_snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('work_kind', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('domain_outcome', sa.String(length=32), nullable=True),
    sa.Column('outcome_detail', sa.JSON(), nullable=False),
    sa.Column('coverage_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('coverage_summary', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('side_effect_class', sa.String(length=32), nullable=False),
    sa.Column('external_idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('reconciliation_required', sa.Boolean(), nullable=False),
    sa.Column('resource_profile', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('output_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("domain_outcome IS NULL OR domain_outcome IN ('COMPLETE','DEGRADED','BOUNDED')", name='ck_execution_domain_outcome'),
    sa.CheckConstraint("side_effect_class != 'EXTERNAL_SIDE_EFFECT' OR external_idempotency_key IS NOT NULL", name='ck_execution_external_identity'),
    sa.CheckConstraint("side_effect_class IN ('SAFE_RECOMPUTATION','EXTERNAL_SIDE_EFFECT')", name='ck_execution_side_effect_class'),
    sa.CheckConstraint("state IN ('QUEUED','ADMITTED','READY','LEASED','RUNNING','RETRY_WAIT','SUCCEEDED','FAILED','CANCELLED','TIMED_OUT')", name='ck_execution_work_state'),
    sa.CheckConstraint("state NOT IN ('SUCCEEDED','FAILED','CANCELLED','TIMED_OUT') OR terminal_at IS NOT NULL", name='ck_execution_terminal_timestamp'),
    sa.CheckConstraint('attempt_count >= 0 AND max_attempts > 0', name='ck_execution_attempt_bounds'),
    sa.CheckConstraint('priority >= 0 AND priority <= 100', name='ck_execution_priority'),
    sa.CheckConstraint('version >= 0', name='ck_execution_work_version'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'work_kind', 'external_idempotency_key', name='uq_execution_external_idempotency'),
    sa.UniqueConstraint('tenant_id', 'work_kind', 'idempotency_key', name='uq_execution_work_idempotency')
    )
    with op.batch_alter_table('execution_work_items', schema=None) as batch_op:
        batch_op.create_index('ix_execution_claim', ['state', 'available_at', 'priority', 'created_at'], unique=False)
        batch_op.create_index('ix_execution_subject', ['tenant_id', 'resource_type', 'resource_id'], unique=False)
        batch_op.create_index('ix_execution_tenant_active', ['tenant_id', 'state'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_coverage_artifact_id'), ['coverage_artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_deadline_at'), ['deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_policy_snapshot_id'), ['policy_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_resource_profile'), ['resource_profile'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_work_items_work_kind'), ['work_kind'], unique=False)

    op.create_table('artifact_deletion_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tombstone_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('observed_digest', sa.String(length=64), nullable=True),
    sa.Column('blocker_codes', sa.JSON(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('DELETED','BLOCKED','RETRYABLE_FAILURE','PERMANENT_FAILURE')", name='ck_artifact_deletion_outcome'),
    sa.ForeignKeyConstraint(['tombstone_id'], ['artifact_tombstones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_deletion_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_deletion_attempts_attempted_at'), ['attempted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_deletion_attempts_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_deletion_attempts_tombstone_id'), ['tombstone_id'], unique=False)
        batch_op.create_index('ix_artifact_deletion_tombstone_time', ['tombstone_id', 'attempted_at'], unique=False)

    op.create_table('artifact_reference_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['artifact_references.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id', name='uq_artifact_reference_release')
    )
    with op.batch_alter_table('artifact_reference_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_reference_releases_reference_id'), ['reference_id'], unique=False)

    op.create_table('execution_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('policy_snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_sequence', sa.Integer(), nullable=False),
    sa.Column('side_effect_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side_effect_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_operation_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('LEASED','RUNNING','SUCCEEDED','FAILED','CANCELLED','TIMED_OUT')", name='ck_execution_attempt_state'),
    sa.CheckConstraint('attempt_number > 0', name='ck_execution_attempt_positive'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'attempt_number', name='uq_execution_attempt_number')
    )
    with op.batch_alter_table('execution_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_attempts_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_attempts_work_item_id'), ['work_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_attempts_worker_id'), ['worker_id'], unique=False)

    op.create_table('execution_request_budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('max_wall_clock_seconds', sa.Integer(), nullable=False),
    sa.Column('max_analyzer_seconds', sa.Integer(), nullable=False),
    sa.Column('max_ai_calls', sa.Integer(), nullable=False),
    sa.Column('max_input_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('max_escalation_tier', sa.Integer(), nullable=False),
    sa.Column('max_retrieval_context_tokens', sa.Integer(), nullable=False),
    sa.Column('max_embedding_calls', sa.Integer(), nullable=False),
    sa.Column('max_report_bytes', sa.Integer(), nullable=False),
    sa.Column('max_report_pages', sa.Integer(), nullable=False),
    sa.Column('used_analyzer_seconds', sa.Integer(), nullable=False),
    sa.Column('used_ai_calls', sa.Integer(), nullable=False),
    sa.Column('used_input_tokens', sa.Integer(), nullable=False),
    sa.Column('used_output_tokens', sa.Integer(), nullable=False),
    sa.Column('used_escalation_tier', sa.Integer(), nullable=False),
    sa.Column('used_retrieval_context_tokens', sa.Integer(), nullable=False),
    sa.Column('used_embedding_calls', sa.Integer(), nullable=False),
    sa.Column('used_report_bytes', sa.Integer(), nullable=False),
    sa.Column('used_report_pages', sa.Integer(), nullable=False),
    sa.Column('exhausted_dimension', sa.String(length=64), nullable=True),
    sa.Column('exhausted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_explanation', sa.Text(), nullable=True),
    sa.Column('wall_clock_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_wall_clock_seconds > 0 AND max_analyzer_seconds >= 0 AND max_ai_calls >= 0 AND max_input_tokens >= 0 AND max_output_tokens >= 0 AND max_escalation_tier >= 0 AND max_retrieval_context_tokens >= 0 AND max_embedding_calls >= 0 AND max_report_bytes >= 0 AND max_report_pages >= 0', name='ck_execution_budget_limits'),
    sa.CheckConstraint('used_analyzer_seconds >= 0 AND used_ai_calls >= 0 AND used_input_tokens >= 0 AND used_output_tokens >= 0 AND used_escalation_tier >= 0 AND used_retrieval_context_tokens >= 0 AND used_embedding_calls >= 0 AND used_report_bytes >= 0 AND used_report_pages >= 0', name='ck_execution_budget_usage'),
    sa.CheckConstraint('version >= 0', name='ck_execution_budget_version'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', name='uq_execution_budget_work_item')
    )
    with op.batch_alter_table('execution_request_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_request_budgets_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('execution_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('coverage_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence > 0', name='ck_execution_checkpoint_sequence'),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'sequence', name='uq_execution_checkpoint_sequence')
    )
    with op.batch_alter_table('execution_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_checkpoints_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_checkpoints_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('execution_failure_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('infrastructure_state', sa.String(length=32), nullable=False),
    sa.Column('public_message', sa.String(length=512), nullable=False),
    sa.Column('internal_detail_digest', sa.String(length=64), nullable=True),
    sa.Column('failure_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('USER','REPOSITORY','ANALYZER','PROVIDER','MODEL','BUDGET','WORKFLOW','WORKER','EXTERNAL','INTERNAL')", name='ck_execution_failure_category'),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_failure_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_failure_records_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_failure_records_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_failure_records_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('execution_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('ACTIVE','RELEASED','EXPIRED','REVOKED')", name='ck_execution_lease_state'),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_execution_lease_attempt')
    )
    with op.batch_alter_table('execution_leases', schema=None) as batch_op:
        batch_op.create_index('ix_execution_lease_recovery', ['state', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_leases_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_leases_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_leases_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_leases_work_item_id'), ['work_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_leases_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index('uq_execution_active_lease_per_work_item', ['work_item_id'], unique=True, sqlite_where=sa.text("state = 'ACTIVE'"), postgresql_where=sa.text("state = 'ACTIVE'"))

    op.create_table('execution_resource_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('ACTIVE','RELEASED','EXPIRED','REVOKED')", name='ck_execution_reservation_state'),
    sa.CheckConstraint('units > 0', name='ck_execution_reservation_units'),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lease_id'], ['execution_leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['execution_resource_pools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_item_id'], ['execution_work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'pool_id', name='uq_execution_reservation_lease_pool')
    )
    with op.batch_alter_table('execution_resource_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_execution_reservation_recovery', ['state', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_lease_id'), ['lease_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_pool_id'), ['pool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_resource_reservations_work_item_id'), ['work_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_resource_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_state'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_pool_id'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_lease_id'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_reservations_attempt_id'))
        batch_op.drop_index('ix_execution_reservation_recovery')

    op.drop_table('execution_resource_reservations')
    with op.batch_alter_table('execution_leases', schema=None) as batch_op:
        batch_op.drop_index('uq_execution_active_lease_per_work_item', sqlite_where=sa.text("state = 'ACTIVE'"), postgresql_where=sa.text("state = 'ACTIVE'"))
        batch_op.drop_index(batch_op.f('ix_execution_leases_worker_id'))
        batch_op.drop_index(batch_op.f('ix_execution_leases_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_execution_leases_state'))
        batch_op.drop_index(batch_op.f('ix_execution_leases_expires_at'))
        batch_op.drop_index(batch_op.f('ix_execution_leases_attempt_id'))
        batch_op.drop_index('ix_execution_lease_recovery')

    op.drop_table('execution_leases')
    with op.batch_alter_table('execution_failure_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_failure_records_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_execution_failure_records_code'))
        batch_op.drop_index(batch_op.f('ix_execution_failure_records_attempt_id'))

    op.drop_table('execution_failure_records')
    with op.batch_alter_table('execution_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_checkpoints_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_execution_checkpoints_attempt_id'))

    op.drop_table('execution_checkpoints')
    with op.batch_alter_table('execution_request_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_request_budgets_work_item_id'))

    op.drop_table('execution_request_budgets')
    with op.batch_alter_table('execution_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_attempts_worker_id'))
        batch_op.drop_index(batch_op.f('ix_execution_attempts_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_execution_attempts_state'))

    op.drop_table('execution_attempts')
    with op.batch_alter_table('artifact_reference_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_reference_releases_reference_id'))

    op.drop_table('artifact_reference_releases')
    with op.batch_alter_table('artifact_deletion_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_deletion_tombstone_time')
        batch_op.drop_index(batch_op.f('ix_artifact_deletion_attempts_tombstone_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_deletion_attempts_outcome'))
        batch_op.drop_index(batch_op.f('ix_artifact_deletion_attempts_attempted_at'))

    op.drop_table('artifact_deletion_attempts')
    with op.batch_alter_table('execution_work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_work_items_work_kind'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_state'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_resource_profile'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_request_id'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_policy_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_coverage_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_execution_work_items_available_at'))
        batch_op.drop_index('ix_execution_tenant_active')
        batch_op.drop_index('ix_execution_subject')
        batch_op.drop_index('ix_execution_claim')

    op.drop_table('execution_work_items')
    with op.batch_alter_table('artifact_tombstones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_tombstones_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_tombstones_requested_at'))
        batch_op.drop_index(batch_op.f('ix_artifact_tombstones_request_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_tombstones_eligible_at'))
        batch_op.drop_index(batch_op.f('ix_artifact_tombstones_artifact_id'))

    op.drop_table('artifact_tombstones')
    with op.batch_alter_table('artifact_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_references_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_references_artifact_id'))

    op.drop_table('artifact_references')
    with op.batch_alter_table('artifact_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_lineage_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_lineage_related_artifact_id'))
        batch_op.drop_index('ix_artifact_lineage_incoming')
        batch_op.drop_index(batch_op.f('ix_artifact_lineage_artifact_id'))

    op.drop_table('artifact_lineage')
    with op.batch_alter_table('ai_quota_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_state'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_request_id'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_execution_id'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_reservations_bucket_id'))

    op.drop_table('ai_quota_reservations')
    with op.batch_alter_table('telemetry_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_metrics_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_metrics_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_metrics_request_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_metrics_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_telemetry_metrics_metric_name'))

    op.drop_table('telemetry_metrics')
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_status'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_resource_type'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_resource_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_next_attempt_at'))

    op.drop_table('reconciliation_records')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_lease_owner'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_lease_expires_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_available_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_aggregate_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_aggregate_id'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('operational_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_policies_tenant_scope'))
        batch_op.drop_index(batch_op.f('ix_operational_policies_content_digest'))
        batch_op.drop_index(batch_op.f('ix_operational_policies_active'))

    op.drop_table('operational_policies')
    with op.batch_alter_table('execution_resource_pools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_resource_pools_scope_id'))
        batch_op.drop_index(batch_op.f('ix_execution_resource_pools_resource_type'))

    op.drop_table('execution_resource_pools')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))

    op.drop_table('audit_events')
    op.drop_table('audit_chain_heads')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_revision_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_retention_class'))
        batch_op.drop_index(batch_op.f('ix_artifacts_repository_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_producer'))
        batch_op.drop_index(batch_op.f('ix_artifacts_policy_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_artifacts_coverage_status'))
        batch_op.drop_index(batch_op.f('ix_artifacts_content_digest'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))
        batch_op.drop_index('ix_artifact_revision_type')

    op.drop_table('artifacts')
    with op.batch_alter_table('ai_quota_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_quota_buckets_window_key'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_buckets_window_ends_at'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_buckets_scope_id'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_buckets_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_quota_buckets_model'))

    op.drop_table('ai_quota_buckets')
    with op.batch_alter_table('ai_provider_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_health_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_provider_health_opened_until'))
        batch_op.drop_index(batch_op.f('ix_ai_provider_health_model'))
        batch_op.drop_index(batch_op.f('ix_ai_provider_health_circuit_state'))

    op.drop_table('ai_provider_health')
    with op.batch_alter_table('ai_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_executions_artifact_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_request_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_quota_reservation_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_prompt_digest'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_policy_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_parent_execution_id'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_model'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_evidence_digest'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_capability'))
        batch_op.drop_index(batch_op.f('ix_ai_executions_attempt_id'))

    op.drop_table('ai_executions')
    # ### end Alembic commands ###
