"""Finding schema representing code health, security, or architectural observations."""

from datetime import datetime, timezone
from typing import List, Optional
from uuid import UUID, uuid4
from pydantic import BaseModel, Field
from app.schemas.enums import FindingStatus, Severity
from app.schemas.evidence import Evidence, EvidenceCreate
from app.schemas.metadata import ModelExecutionMetadata


def _utc_now() -> datetime:
    """Return timezone-aware current UTC datetime."""
    return datetime.now(timezone.utc)


class FindingBase(BaseModel):
    """Base fields for a finding."""

    title: str = Field(..., description="Short descriptive title of the finding")
    description: str = Field(..., description="Detailed explanation of the issue or insight")
    severity: Severity = Field(..., description="Assessed severity level")
    status: FindingStatus = Field(default=FindingStatus.OPEN, description="Current resolution status")
    rule_id: Optional[str] = Field(default=None, description="Identifier of the rule or pattern matched")
    category: Optional[str] = Field(default=None, description="Category (e.g. security, performance, style, architecture)")
    mitigation_guidance: Optional[str] = Field(default=None, description="Recommended remediation steps or code diff")


class FindingCreate(FindingBase):
    """Schema for creating a finding."""

    scan_id: UUID = Field(..., description="Identifier of the scan this finding belongs to")
    evidences: List[EvidenceCreate] = Field(default_factory=list, description="Associated code evidences")
    model_metadata: Optional[ModelExecutionMetadata] = Field(default=None, description="Model execution details if generated by AI")


class FindingUpdate(BaseModel):
    """Schema for modifying a finding's status or notes."""

    status: Optional[FindingStatus] = None
    mitigation_guidance: Optional[str] = None


class Finding(FindingBase):
    """Canonical domain schema for a Finding."""

    id: UUID = Field(default_factory=uuid4, description="Unique identifier of the finding")
    scan_id: UUID = Field(..., description="Identifier of the parent scan")
    evidences: List[Evidence] = Field(default_factory=list, description="Associated code evidences")
    model_metadata: Optional[ModelExecutionMetadata] = Field(default=None, description="Model execution details if generated by AI")
    created_at: datetime = Field(default_factory=_utc_now, description="Timestamp when finding was detected")
    updated_at: datetime = Field(default_factory=_utc_now, description="Timestamp when finding was last updated")

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": "a7b93802-f81d-44a7-b12e-18868846c4f1",
                "scan_id": "e2c3a5f9-3d71-4be5-a83d-9d7a9602e1c9",
                "title": "Unverified JWT Token Signature",
                "description": "JWT tokens are parsed with signature verification disabled.",
                "severity": "HIGH",
                "status": "OPEN",
                "rule_id": "SEC-AUTH-001",
                "category": "security",
                "evidences": [
                    {
                        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                        "file_path": "src/auth/jwt.py",
                        "start_line": 42,
                        "end_line": 48,
                        "code_snippet": "jwt.decode(token, verify=False)",
                        "context_notes": "Unverified JWT signature."
                    }
                ],
                "mitigation_guidance": "Enable signature verification using secret key: jwt.decode(token, key=SECRET, algorithms=['HS256'])",
                "created_at": "2026-08-20T10:00:00Z",
                "updated_at": "2026-08-20T10:00:00Z"
            }
        }
    }
